### ISSUE TITLE
The current user doesn't get auto-added

### ISSUE THREAD

**Issue by thegcat** [rchady/redmine_auto_watchers#1]
The end of that line http://github.com/rchady/redmine_auto_watchers/blob/master/lib/auto_watchers/hooks/auto_watchers_issue_hook.rb#L16 should read User.current instead of User.current.id

**Comment by giddie** [comment]
Seconded.  Maybe the behaviour of the `Issue#addable_watcher_users` method changed?  Either way, that method currently returns an array of `User` objects, so it should be tested for inclusion of `User.current`, not `User.current.id`.

**Comment by thegcat** [comment]
I had pondered forking this plugin as it seems rchady doesn't maintain it anymore… I'll send him a message to inquire about his status.

**Comment by thegcat** [comment]
Ok, I had a short discussion with rchady and will take over at least this plugin, probably this WE.

**Comment by ahitrin** [comment]
> should read User.current instead of User.current.id

Yes. After removing .id current user is being added automatically.

**Comment by rchady** [comment]
Doing some housecleaning.
